### ISSUE TITLE
Factory restore for NSPanel

### ISSUE THREAD

**Issue by zeridon** [masto/NSPanel-Demo-Files#4]
I am looking for a way to factory restore the NSPanel.

What i mean by factory restore is to flash the original HMI interface and the original BIN for the esp32.

Getting backup for the ESP is easy and i have done it. Now how to do the HMI/TFT part? or is there some place where i can get the original TFT. HMI would be much nicer but beggars can't be choosers.

**Comment by ilexpl01** [comment]
There You have it:

https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft

**Comment by kernelkraut** [comment]
FYI - https://discord.com/channels/538814618106331137/538814618106331139/953307169422450718 (US)

**Comment by Scannow** [comment]
Hello, the second link (US version) does not work anymore. Have someone a backup? Thanks!

**Comment by ChrisVonFrosta** [comment]
> There You have it:
> 
> https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft

DIsplay says: "Model does not match"

**Comment by danir-de** [comment]
> There You have it:
> 
> https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft

The link sadly doesn't work anymore. Is there an updated url?

**Comment by madmagic007** [comment]
> There You have it:
> 
> https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft

Discords new attachment urls breaks this. anyone have a new link?

**Comment by sephdoto** [comment]
Same! Would like to have it too!

> > There You have it:
> > https://cdn.discordapp.com/attachments/538814618106331139/925351768852951050/ns-panel.tft
> 
> DIsplay says: "Model does not match"

**Comment by bennydiamond** [comment]
Could somebody please re-upload the tft files. They seem to have been deleted by discord.
I need the US variant specifically but having both available could be nice.

thanks.

**Comment by ilexpl01** [comment]
Have a look here:

https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/main/hmi

**Comment by craggyh** [comment]
Does anybody have a link to original EU firmware bin file?

**Comment by maxromanovsky** [comment]
@ilexpl01 just to be clear, do you mean that [here (https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/main/hmi)](https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/main/hmi) are the stock firmware files for NSPanel, in case we want to rollback from the custom firmware?

https://github.com/masto/NSPanel-Demo-Files/issues/4#issuecomment-1034608391

**Comment by craggyh** [comment]
From what I can see these are the factory files for the screen, not the NSPanel itself. I don’t see any .bin files there for the esp32.

**Comment by masto** [comment]
Hey folks. Couple of things:

1. There is no way to restore the *original firmware* (the one that it comes with, that works with their app) unless you backed it up before flashing. The firmware is locked to the device, so you can't use someone else's copy.

2. While you can restore the original TFT, Sonoff considers that file their property. It is not open source, they have not shared it, and they have not given permission for anyone else to share it. When it pops up somewhere, it gets taken down.

If you have already flashed your device and you're trying to restore because you can't get it working, my suggestion is to follow something like https://github.com/Blackymas/NSPanel_HA_Blueprint. The tutorial video I made 2 years ago was before other folks had built these turnkey solutions, and it's a very low-level DIY approach. It still works if you want a fully custom design, but most of the time it will be a lot easier to use the existing building blocks.

I am going to lock this issue because people turning up here from Google searches, but there's nothing in this repo that can help folks with a factory restore. These files and wiki were intended to facilitate the homebrew approach.
